### PR TITLE
Fix typo in "Getting Started" section on index page

### PR DESCRIPTION
**Pull request by Ace4896**
**What kind of change does this PR introduce?**

Fixes a typo in the "Getting Started" section on the index page.

**What is the current behavior?**

> See our quickstart guide for information on how to get started with Avalonia using JetBrains Rider, Visual Studio or the **.NET command-line. core.**

**What is the new behavior?**

> See our quickstart guide for information on how to get started with Avalonia using JetBrains Rider, Visual Studio or the **.NET command-line.**

### CODE REVIEW

**Comment by FoggyFinder** [comment]
I'd keep `.NET command-line` since there is no .Net Core already.

**Comment by Ace4896** [comment]
Oh right, I forgot they removed it altogether.

**Comment by danwalmsley** [comment]
we have a new website.

**Comment by Ace4896** [comment]
Ah, I wasn't aware that it was in the works when I made this PR, the new site looks really good!

**Pull request closed without merging**
